import { T3_MOVE, T3_NEW_GAME, SET_MODULE_STATUS, SHOW_OPTIONS, SHOW_T3_OPEN_MOVES, HANDLE_INPUT, RENDER_MODULE, T3_GAME_CHECK, } from '../helpers/actionTypes';
import { T3_MOVE_FN, SET_MODULE_STATUS_FN, SHOW_OPTIONS_FN, SHOW_T3_OPEN_MOVES_FN, HANDLE_INPUT_FN, RENDER_MODULE_FN, T3_GAME_CHECK_FN, T3_NEW_GAME_FN } from './executionTableFuncs';

export const executionTable = {
	[T3_MOVE]: T3_MOVE_FN,
	[SET_MODULE_STATUS]: SET_MODULE_STATUS_FN,
	[SHOW_OPTIONS]: SHOW_OPTIONS_FN,
	[SHOW_T3_OPEN_MOVES]: SHOW_T3_OPEN_MOVES_FN,
	[HANDLE_INPUT]: HANDLE_INPUT_FN,
	[RENDER_MODULE]: RENDER_MODULE_FN,
	[T3_GAME_CHECK]: T3_GAME_CHECK_FN,
	[T3_NEW_GAME]: T3_NEW_GAME_FN,
}
